name: environment test

on: 
  workflow_dispatch:

jobs:
  get-repo-name:
    runs-on: ubuntu-latest
    
    steps:
      - name: get data 
        run: |
          repo_name=${GITHUB_REPOSITORY##*/}
          owner_name=${GITHUB_REPOSITORY%/*}
      - name: show data 
        run: |
          echo "Repository Name: $repo_name"
          echo "Owner Name: $owner_name"
